### ISSUE TITLE
Update MWDI release number and nr/or info

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#1114]
current oldRelease block in serviceList:
```
  - http-client:
      application-name: MicroWaveDeviceInventory
      release-number: 1.1.0                                               #<----- change to 1.2.1
      uuid: mwdi-1-2-2-http-c-or-1-2-1-000                    # <---- uuids with or-1-2-1 remain
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.4.4
      tcp-port: 4004
      uuid: mwdi-1-2-2-tcp-c-or-1-2-1-000
    operation-clients:
      own-oam:
        basic:
          - operation-name: /v1/bequeath-your-data-and-die
            uuid: mwdi-1-2-2-op-c-bm-or-1-2-1-000
...
```

newRelease block:
```
  - http-client:
      application-name: NewRelease
      release-number: 1.2.1                                          #<---- change to 1.2.2
      uuid: mwdi-1-2-2-http-c-nr-1-2-2-000               #<---- uuids already correct
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port: 4023
      uuid: mwdi-1-2-2-tcp-c-nr-1-2-2-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - operation-name: /v1/notify-attribute-value-changes
            uuid: mwdi-1-2-2-op-c-im-nr-1-2-2-000
          - operation-name: /v1/notify-object-creations
            uuid: mwdi-1-2-2-op-c-im-nr-1-2-2-001
          - operation-name: /v1/notify-object-deletions
            uuid: mwdi-1-2-2-op-c-im-nr-1-2-2-002
      service:
        basic:
        individual:
```
