### ISSUE TITLE
Add new deviceType attribute to /v1/provide-device-status-metadata response

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#1156]
Currently the service response looks as follows and contains only the schema-cache-directory to indicate the vendor/deviceType
```
device-status-metadata:
  - mount-name: '305251234'
    connection-status: 'connected'
    changed-to-disconnected-time: ''
    added-to-device-list-time: '2024-10-10T14:00:00+01:00'
    last-complete-control-construct-update-time: '2024-10-10T14:00:05+01:00'
    last-control-construct-notification-update-time: '2024-10-10T15:17:00+01:00'
    number-of-partial-updates-since-last-complete-update: 7
    schema-cache-directory: 'hua'
```

Add another attribute with device-type.

---
**Find suitable attribute in CC data**
Looking into CCs of lab devices provided promising results when looking at attribute:
`/core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-capability/type-of-equipment`

Extractable via fields filter: `?fields=logical-termination-point(layer-protocol(air-interface-2-0:air-interface-pac(air-interface-capability(type-of-equipment))))`

**Found attribute values**
Found examples did not just include the deviceType but additional info (as the info is about the air interface equipment).
Also it might be the case that the notation is not always the same across deviceTypes (e.g. there may be different releases for a deviceType coming with different values)

Seen type-of-equipment values in lab e.g. were (parts which are not deviceType are replace in example):
- MINI-LINK 6363 23/xyz
- OptiXRTN380AX/abc/efg
- MINI-LINK 6363 23/xyz
- ALCplus2e
- AGS-20
- OptiXRTN950N/ijh/mln

**Which returned data is relevant**
- The fields filter will not only return the data that's needed, but it will return all ltps it finds in the CC
- therefore all records without air-interface-capability/type-of-equipment can be ignored
- and also a device's CC can contain multiple air-interface-capability/type-of-equipment records which may hold duplicate information (i.e. the deviceType that can be extracted from it, is the same)
- also a CC may contain air-interface-capability/type-of-equipment information which cannot be mapped against a known deviceType

**How extract the deviceType from the type-of-equipment (regex)**
- Apply regex to find the deviceType in the raw attribute
- if the raw deviceType is found normalize it to a specified target value (e.g. normalize AGS-20 to AGS20 or OptiXRTN950N to RTN950, etc.)
- process all found type-of-equipment attributes until a deviceType can be mapped, if none has been found after all records have been processed return something like "unknown" for that device
- normally the extractable deviceType should not be different inside a given device (e.g. not one type-of-equipment leading to "RTN380" and another leading to "RTN950"), so it could be assumed that process can stop once a mapping has been found (but assumption might need to be validated against data from live NEs) 

**How to maintain the regex patterns to be used**
- The patterns could be provided via a profileInstance. Said profileInstance can have a enum of patterns (or strings which will be compiled internally to the patterns)
- this would allow to easily add new or remove no longer needed patterns
- if this would be a new profile type new management services would have to be added to the OAS
- pattern changes could be applied at runtime, ensuring that if e.g. new deviceTypes are added to the network, MWDI could handle those without having to provide a new MWDI software release
- string profile definition contains an enumeration, which could be used to provide the patterns, but there's no option to add a mapping, therefore a new profile shall be added
