### ISSUE TITLE
Add new oam layer services for new profile RegexPatternMappingProfile

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#1157]
The OAS needs to provide OAM layer services for managing profileInstances. As a new profile type is required for the regex mapping, related services also neeed to be added to OAS (and also to configFile possibly).

Currently MWDI has the following ones:

![Image](https://github.com/user-attachments/assets/85928617-9696-436d-8989-64f64b1cb2dc)

The new pattern currently looks as follows:
```
  - profile-name: 'RegexPatternMappingProfile'
    uuid: '^[a-z]{2,6}-([0-9]+)-([0-9]+)-([0-9]+)-mapping-p-[0-9]{3}$'
    capability:
      mapping-name: string
      mapping-list:
        - regex-string: string
          map-to-string: string 
    configuration:
        - regex-string: string
          map-to-string: string
```
