### ISSUE TITLE
[Clarification] Kommunikation mit Controller: Protokoll?

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#118]
Wie muss mit dem Controller kommuniziert werden?
- Annahme: via https
- dann müsste in der ServiceList `remote-protocol` wohl zu https geändert werden
```
  - http-client:
      application-name: OpenDaylight
      release-number: 1.0.0
      uuid: mwdi-1-0-0-http-c-c-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.1.1
      tcp-port: 1001
      uuid: mwdi-1-0-0-tcp-c-c-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
          ## DONE: Add Clients specific to this application, but addressing all other applications
          ## none
        individual:
          ## get list of (all) mounted devices on the controller with connection status
          - operation-name: /rests/data/network-topology:network-topology/topology=topology-netconf?fields=node(node-id;node-id;netconf-node-topology:connection-status)
            uuid: mwdi-1-0-0-op-c-is-c-1-0-0-000
          ## get control construct for a given device
          - operation-name: /rests/data/network-topology:network-topology/topology=topology-netconf/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct
            uuid: mwdi-1-0-0-op-c-is-c-1-0-0-001
```
