### ISSUE TITLE
Add missing callbacks to OAS

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#1194]
Check which of the cyclic process callbacks are still missing from OAS.

Callbacks from qualityMeasurement diagram have already been added (fc-im-04*)

**Comment by kmohr-soprasteria** [comment]
Missing are (those which are ElasticSearch normally are not added; check for which here adding them is required):
```
  - forwarding-name: PromptForEmbeddingCausesDeletingUnconnectedDevicesFromCache
    uuid: mwdi-1-3-0-op-fc-im-004
    consequent-requests:
      - client-name: ElasticSearch://control-construct={mountName}
        uuid: mwdi-1-3-0-op-c-del-es-1-0-0-700

  - forwarding-name: PromptForEmbeddingCausesRetrievingNextSlidingWindowCandidateDeviceFromMetadataTable
    uuid: mwdi-1-3-0-op-fc-im-005
    consequent-requests:
      - client-name: MicroWaveDeviceInventory://v1/provide-device-status-metadata
        uuid: mwdi-1-3-0-op-c-is-mwdi-1-3-0-018

  - forwarding-name: PromptForEmbeddingCausesUpdatingMetadataTableInElasticSearchFromDeviceListSync
    uuid: mwdi-1-3-0-op-fc-im-006
    consequent-requests:
      - client-name: ElasticSearch
        uuid: mwdi-1-3-0-es-c-es-1-0-0-000

  - forwarding-name: PromptForEmbeddingCausesSelfCallingForLoadingOfControlConstructForDevicesNotInCache
    uuid: mwdi-1-3-0-op-fc-im-007
    consequent-requests:
      - client-name: MicroWaveDeviceInventory://core-model-1-4:network-control-domain=live/control-construct={mountName}
        uuid: mwdi-1-3-0-op-c-is-mwdi-1-3-0-400
```
