### ISSUE TITLE
Update of fc-is callbacks handling updates of device metadata due to notifications

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#1217]
The following forwardings have been removed from fowardingList and configFile:

```
(is-001) NotifiedNewDeviceCausesMetadataTableUpdate
(is-002) NotifiedDisconnectedDeviceCausesDeviceDeletionFromCache
(is-003) NotifiedDisconnectedDeviceCausesMetadataTableUpdate
(is-007) NotifiedDeviceAttributeValueChangeCausesMetadataTableUpdate
(is-009) NotifiedDeviceObjectCreationCausesMetadataTableUpdate
(is-011) NotifiedDeviceObjectDeletionCausesMetadataTableUpdate
```

Todo:
- [ ] consolidate forwardings in forwardingList
- [ ] consolidate forwardings in configFile
- [ ] consolidate diagrams
- [ ] consolidate OAS

Note:
- metadataTable has been replaced by deviceMetadataList
- but: change is still not straight-forward, because Notifications will not be received by NP directly anymore, but via Kafka!

**Comment by kmohr-soprasteria** [comment]
ForwardingList:
```

  - forwarding-name: NotifiedNewDeviceCausesMetadataTableUpdate
    uuid: mwdi-1-3-0-op-fc-is-001
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/regard-controller-attribute-value-change
        uuid: mwdi-1-3-0-op-s-is-000
    consequent-requests:
      - client-name: ElasticSearch
        uuid: mwdi-1-3-0-es-c-es-1-0-0-000

  - forwarding-name: NotifiedDisconnectedDeviceCausesDeviceDeletionFromCache
    uuid: mwdi-1-3-0-op-fc-is-002
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/regard-controller-attribute-value-change
        uuid: mwdi-1-3-0-op-s-is-000
    consequent-requests:
      - client-name: ElasticSearch://control-construct={mountName}
        uuid: mwdi-1-3-0-op-c-del-es-1-0-0-700

  - forwarding-name: NotifiedDisconnectedDeviceCausesMetadataTableUpdate
    uuid: mwdi-1-3-0-op-fc-is-003
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/regard-controller-attribute-value-change
        uuid: mwdi-1-3-0-op-s-is-000
    consequent-requests:
      - client-name: ElasticSearch
        uuid: mwdi-1-3-0-es-c-es-1-0-0-000

  - forwarding-name: NotifiedDeviceAttributeValueChangeCausesMetadataTableUpdate
    uuid: mwdi-1-3-0-op-fc-is-007
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/regard-device-attribute-value-change
        uuid: mwdi-1-3-0-op-s-is-003
    consequent-requests:
      - client-name: ElasticSearch
        uuid: mwdi-1-3-0-es-c-es-1-0-0-000

  - forwarding-name: NotifiedDeviceObjectCreationCausesMetadataTableUpdate
    uuid: mwdi-1-3-0-op-fc-is-009
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/regard-device-object-creation
        uuid: mwdi-1-3-0-op-s-is-004
    consequent-requests:
      - client-name: ElasticSearch
        uuid: mwdi-1-3-0-es-c-es-1-0-0-000


  - forwarding-name: NotifiedDeviceObjectDeletionCausesMetadataTableUpdate
    uuid: mwdi-1-3-0-op-fc-is-011
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/regard-device-object-deletion
        uuid: mwdi-1-3-0-op-s-is-005
    consequent-requests:
      - client-name: ElasticSearch
        uuid: mwdi-1-3-0-es-c-es-1-0-0-000
```
