### ISSUE TITLE
(Notifications) Rollback deprecation of regard-services, remove NotificationProxy client stuff

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#1249]
The regard services can be called to handover a notification to MWDI, which then is processesd according to the specified callbacks.
In the past the services were called by NotificationProxy.

They can be kept and instead simply be called internally from MWDI.
I.e. there can be a process to constantly listen to new notifications on Kafka and fetch them to MWDI. Depending on which notification was fetched, the related regard service is called.

**Comment by kmohr-soprasteria** [comment]
NP operation client removed from serviceList:
```
  - http-client:
      application-name: NotificationProxy
      release-number: 1.0.2
      uuid: mwdi-1-3-0-http-c-np-1-0-2-000
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port: 4011
      uuid: mwdi-1-3-0-tcp-c-np-1-0-2-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
        individual:
          ## subscribing for controller notifications
          - operation-name: /v1/notify-controller-attribute-value-changes
            uuid: mwdi-1-3-0-op-c-is-np-1-0-2-000

          ## subscribing for device notifications
          - operation-name: /v1/notify-device-alarms
            uuid: mwdi-1-3-0-op-c-is-np-1-0-2-010
          - operation-name: /v1/notify-device-attribute-value-changes
            uuid: mwdi-1-3-0-op-c-is-np-1-0-2-011
          - operation-name: /v1/notify-device-object-creations
            uuid: mwdi-1-3-0-op-c-is-np-1-0-2-012
          - operation-name: /v1/notify-device-object-deletions
            uuid: mwdi-1-3-0-op-c-is-np-1-0-2-013

          ## unsubscribe from notifications
          - operation-name: /v1/end-subscription
            uuid: mwdi-1-3-0-op-c-is-np-1-0-2-020
```
