### ISSUE TITLE
(Notifications) Add new callbacks to OAS

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#1258]
Update the OAS according to the following forwardings:
```

  - forwarding-name: PromptForEmbeddingCausesSubscribingForNotificationsAtKafka
    uuid: mwdi-1-3-0-op-fc-im-000
    initiating-requests:
      - server-name: /v1/embed-yourself
        uuid: mwdi-1-3-0-op-s-bm-001
    consequent-requests:
      - client-name: KafkaMessageBroker
        uuid: mwdi-1-3-0-kmb-c-kmb-1-0-0-000

  - forwarding-name: PromptForEmbeddingCausesCylicPollingOfProperNotificationsFromKafka
    uuid: mwdi-1-3-0-op-fc-im-001
    initiating-requests:
      - server-name: /v1/embed-yourself
        uuid: mwdi-1-3-0-op-s-bm-001
    consequent-requests:
      - client-name: KafkaMessageBroker
        uuid: mwdi-1-3-0-kmb-c-kmb-1-0-0-000

  - forwarding-name: PromptForEmbeddingCausesCyclicNotificationProcessingToCallRegardControllerAttributeValueChange
    uuid: mwdi-1-3-0-op-fc-im-002
    initiating-requests:
      - server-name: /v1/embed-yourself
        uuid: mwdi-1-3-0-op-s-bm-001
    consequent-requests:
      - client-name: MWDI://v1/regard-controller-attribute-value-change
        uuid: mwdi-1-3-0-op-c-is-mwdi-1-3-0-000

  - forwarding-name: PromptForEmbeddingCausesCyclicNotificationProcessingToCallRegardDeviceAlarm
    uuid: mwdi-1-3-0-op-fc-im-003
    initiating-requests:
      - server-name: /v1/embed-yourself
        uuid: mwdi-1-3-0-op-s-bm-001
    consequent-requests:
      - client-name: MWDI://v1/regard-device-alarm
        uuid: mwdi-1-3-0-op-c-is-mwdi-1-3-0-002

  - forwarding-name: PromptForEmbeddingCausesCyclicNotificationProcessingToCallRegardDeviceAttributeValueChange
    uuid: mwdi-1-3-0-op-fc-im-004
    initiating-requests:
      - server-name: /v1/embed-yourself
        uuid: mwdi-1-3-0-op-s-bm-001
    consequent-requests:
      - client-name: MWDI://v1/regard-device-attribute-value-change
        uuid: mwdi-1-3-0-op-c-is-mwdi-1-3-0-003

  - forwarding-name: PromptForEmbeddingCausesCyclicNotificationProcessingToCallRegardDeviceObjectCreation
    uuid: mwdi-1-3-0-op-fc-im-005
    initiating-requests:
      - server-name: /v1/embed-yourself
        uuid: mwdi-1-3-0-op-s-bm-001
    consequent-requests:
      - client-name: MWDI://v1/regard-device-object-creation
        uuid: mwdi-1-3-0-op-c-is-mwdi-1-3-0-004

  - forwarding-name: PromptForEmbeddingCausesCyclicNotificationProcessingToCallRegardDeviceObjectDeletion
    uuid: mwdi-1-3-0-op-fc-im-006
    initiating-requests:
      - server-name: /v1/embed-yourself
        uuid: mwdi-1-3-0-op-s-bm-001
    consequent-requests:
      - client-name: MWDI://v1/regard-device-object-deletion
        uuid: mwdi-1-3-0-op-c-is-mwdi-1-3-0-005

  - forwarding-name: PromptForBequeathingDataCausesUnsubscribingFromDeviceAndControllerNotificationsAtKafka
    uuid: mwdi-1-3-0-op-fc-im-115
    initiating-requests:
      - server-name: /v1/bequeath-your-data-and-die
        uuid: mwdi-1-3-0-op-s-im-000
    consequent-requests:
      - client-name: KafkaMessageBroker
        uuid: mwdi-1-3-0-kmb-c-kmb-1-0-0-000
```
