### ISSUE TITLE
[Refine-QM]: replace retentionPeriod profileInstance with sample profileInstance

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#1273]
replace qualityMeasurementRetentionPeriod integer profile by qualityMeasurementSampleNumber (default 1440)

before:
```
  - profile-name: 'IntegerProfile'
    uuid: 'mwdi-2-0-0-integer-p-007'
    capability:
      integer-name: 'qualityMeasurementRetentionPeriod'
      purpose: 'Time period for which qualityMeasurement records are kept, before they are deleted.'
      unit: 'days'
      minimum: 1
      maximum: 30
    configuration:
      integer-value: 7
```
