### ISSUE TITLE
[Refinement-Notifications] Update forwardings for Notification processing

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#1284]

**Comment by kmohr-soprasteria** [comment]
Before:
```
  - forwarding-name: PromptForEmbeddingCausesCyclicNotificationProcessingToCallRegardControllerAttributeValueChange
    uuid: mwdi-2-0-0-op-fc-im-002
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/embed-yourself
        uuid: mwdi-2-0-0-op-s-bm-001
    consequent-requests:
      - client-name: MWDI://v1/regard-controller-attribute-value-change
        uuid: mwdi-2-0-0-op-c-is-mwdi-2-0-0-000

  - forwarding-name: PromptForEmbeddingCausesCyclicNotificationProcessingToCallRegardDeviceAlarm
    uuid: mwdi-2-0-0-op-fc-im-003
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/embed-yourself
        uuid: mwdi-2-0-0-op-s-bm-001
    consequent-requests:
      - client-name: MWDI://v1/regard-device-alarm
        uuid: mwdi-2-0-0-op-c-is-mwdi-2-0-0-002

  - forwarding-name: PromptForEmbeddingCausesCyclicNotificationProcessingToCallRegardDeviceAttributeValueChange
    uuid: mwdi-2-0-0-op-fc-im-004
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/embed-yourself
        uuid: mwdi-2-0-0-op-s-bm-001
    consequent-requests:
      - client-name: MWDI://v1/regard-device-attribute-value-change
        uuid: mwdi-2-0-0-op-c-is-mwdi-2-0-0-003

  - forwarding-name: PromptForEmbeddingCausesCyclicNotificationProcessingToCallRegardDeviceObjectCreation
    uuid: mwdi-2-0-0-op-fc-im-005
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/embed-yourself
        uuid: mwdi-2-0-0-op-s-bm-001
    consequent-requests:
      - client-name: MWDI://v1/regard-device-object-creation
        uuid: mwdi-2-0-0-op-c-is-mwdi-2-0-0-004

  - forwarding-name: PromptForEmbeddingCausesCyclicNotificationProcessingToCallRegardDeviceObjectDeletion
    uuid: mwdi-2-0-0-op-fc-im-006
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/embed-yourself
        uuid: mwdi-2-0-0-op-s-bm-001
    consequent-requests:
      - client-name: MWDI://v1/regard-device-object-deletion
        uuid: mwdi-2-0-0-op-c-is-mwdi-2-0-0-005
```
