### ISSUE TITLE
[Code] Update ForwardingList for v1.0.0 with internal management parts

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#131]
also see #117

- 117 contains notifications/subscriptions to HMDI/controller relevant for bequeath-your-data-and-die
- this issue focusses on adding the forwardings for internal managment of the deviceList and CC retrieval

**Comment by kmohr-soprasteria** [comment]
Beispiele für CyclicOperation Forwarding vom OKM:
```
  - forwarding-name: CyclicOperationCausesRequestForListOfLinks
    uuid: okm-2-0-1-op-fc-is-010
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
    consequent-requests:
      - client-name: ApplicationLayerTopology:://v1/list-link-uuids
        uuid: okm-2-0-1-op-c-is-alt-1-0-0-002

  - forwarding-name: CyclicOperationCausesRequestForLinkEndPoints
    uuid: okm-2-0-1-op-fc-is-011
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
    consequent-requests:
      - client-name: ApplicationLayerTopology:://v1/list-end-points-of-link
        uuid: okm-2-0-1-op-c-is-alt-1-0-0-003

  - forwarding-name: CyclicOperationCausesOperationKeyUpdates
    uuid: okm-2-0-1-op-fc-is-012
    forwarding-type: ProcessSnippet
    management-requests:
      operation-client-update:
        - server-name: /v1/regard-application
          uuid: okm-2-0-1-op-s-is-001
      fc-port-update:
        - server-name: /v1/regard-application
          uuid: okm-2-0-1-op-s-is-001
      fc-port-deletion:
        - server-name: /v1/disregard-application
          uuid: okm-2-0-1-op-s-is-002
      operation-client-deletion:
        - server-name: /v1/disregard-application
          uuid: okm-2-0-1-op-s-is-002
    initiating-requests:
    consequent-requests:
      - client-name: RegistryOffice:://v1/update-operation-key
        uuid: okm-2-0-1-op-c-is-ro-2-0-1-000
      - client-name: TypeApprovalRegister:://v1/update-operation-key
        uuid: okm-2-0-1-op-c-is-tar-1-0-0-000
      - client-name: ExecutionAndTraceLog:://v1/update-operation-key
        uuid: okm-2-0-1-op-c-is-eatl-1-0-0-000
      - client-name: OamLog:://v1/update-operation-key
        uuid: okm-2-0-1-op-c-is-ol-1-0-0-000
      - client-name: AdministratorAdministration:://v1/update-operation-key
        uuid: okm-2-0-1-op-c-is-aa-1-0-0-000
      - client-name: ApplicationLayerTopology:://v1/update-operation-key
        uuid: okm-2-0-1-op-c-is-alt-1-0-0-000
      - client-name: OperationKeyManagement:://v1/update-operation-key
        uuid: okm-2-0-1-op-c-is-okm-2-0-1-000
      - client-name: CurrentController:://v1/update-operation-key
        uuid: okm-2-0-1-op-c-is-cc-1-0-0-000
```
