### ISSUE TITLE
Add a new genericResponseProfileInstance for v2.0.1

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#1321]
Add a new profileInstance similar to
```
  - profile-name: 'GenericResponseProfile'
    uuid: 'mwdi-2-0-0-response-p-010'
    capability:
      operation-name: '/v1/inform-about-release-history-in-generic-representation'
      field-name-reference: '/core-model-1-4:control-construct/logical-termination-point=mwdi-2-0-0-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/release-list=3/release-number'
      description: 'Represents the 4th entry in the list of releases'
      datatype: string
    configuration:
      value-reference: '/core-model-1-4:control-construct/logical-termination-point=mwdi-2-0-0-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/release-list=3/changes'
```

will be release-list=4

also to configFile
