### ISSUE TITLE
Fix linting errors in spec

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#1325]

**Comment by kmohr-soprasteria** [comment]
also modified linter config file:
```
name: Yaml Lint
on:
  pull_request:
    branches: [develop]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          format: github
          config_data: |
            extends: default
            strict: true                        <-  added to ignore warnings and only show errors
            ignore: |
              /server/
              /testing/                        <- exclude testing folder from lint check
            rules:
              line-length: disable
              document-start: disable
```
