### ISSUE TITLE
[Code] Add unsubscribe to Controller device status notification

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#133]
URL für Subscribe & Unsubscribe ist gleich, aber beim Unsubscribe muss sie mit DELETE aufgerufen werden
Unklar, wie genau die Subscription funktioniert, Rückfrage an Senthilvel

s. Issue #87

**Comment by kmohr-soprasteria** [comment]
Vorbereitung der Forwardings, Zwischenstand (muss je nach Antwort von Senthilvel korrigiert werden):

```
## DONE: Potentially add Forwardings for creating INDIVIDUAL subscriptions to NewRelease
# the MWDI only has a subscription to the Controller (which was not implemented following the ApplicationPattern)
# the MWDI needs to listen to the following URL:
# https://<controller_IP>:8443/rests/notif/data-change-event-subscription/network-topology:network-topology/datastore=OPERATIONAL/scope=SUBTREE/JSON
# currently the subscription is done manually by TechM team! (with next ODL release this will no longer be done manually)
# so at the moment the MWDI just needs to listen to the URL, but not actively subscribe
  - forwarding-name: PromptForBequeathingDataCausesControllerBeingRequestedToInquireForDeviceConnectionStatusAtNewMWDI
    uuid: mwdi-1-0-0-op-fc-im-003
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/bequeath-your-data-and-die
        uuid: mwdi-1-0-0-op-s-im-000
    consequent-requests:
      - client-name: OpenDaylight://rests/notif/data-change-event-subscription/network-topology:network-topology/datastore=OPERATIONAL/scope=SUBTREE/JSON
        uuid: mwdi-1-0-0-op-c-is-c-1-0-0-003

## TODO: Potentially add Forwardings for ending INDIVIDUAL subscriptions to OldRelease
# here the subscription to the Controller would need to be canceled
# to cancel the subscription send a DELETE request with the notification URL
  - forwarding-name: PromptForBequeathingDataCausesEndingSubscriptionToOldRelease
    uuid: mwdi-1-0-0-op-fc-im-004
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/bequeath-your-data-and-die
        uuid: mwdi-1-0-0-op-s-im-000
    consequent-requests:
      - client-name: OpenDaylight://rests/notif/data-change-event-subscription/network-topology:network-topology/datastore=OPERATIONAL/scope=SUBTREE/JSON
        uuid: mwdi-1-0-0-op-c-is-c-1-0-0-003
```
