### ISSUE TITLE
Remove profileInstnace notifcationPollingInterval

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#1339]
Polling configuration is handled by Kafka libraries (polling is done continously).
Therefore instance can be removed:

```
  - profile-name: 'IntegerProfile'
    uuid: 'mwdi-2-0-1-integer-p-008'
    capability:
      integer-name: 'notificationPollingInterval'
      purpose: 'Time interval with which MWDI shall poll notifications from Kafka.'
      unit: 'seconds'
      minimum: 0
      maximum: 900
    configuration:
      integer-value: 60
```
