### ISSUE TITLE
[Code] Update ForwardingList for v1.0.0 for LTP changes

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#134]
Description of [LTPs](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/InformationModel/LogicalTerminationPoint/LogicalTerminationPoint.md)

LTPs = termination point of a logical connections, means: it's some sort of interface

---

Process the following todos:

![image](https://user-images.githubusercontent.com/57349523/235863635-e4ddbfc6-4f9a-4f34-9839-12f1bba5ad73.png)

**Comment by kmohr-soprasteria** [comment]
Es sollte keine Services geben, die irgendwelche Verbindungsinformationen ändern, also weder:
- die LTP-Direction (Termination_Direction_Source/Sink)
- den Client-LTP
- den Server-LTP
- das layerProtocol

diese ganzen Infos sollten nur einmal in der Spezifikation angegeben werden und sich danach nicht mehr ändern.

(Thorsten müsste das beim Review dann verifizieren)

**Comment by kmohr-soprasteria** [comment]
RO: no entry for unsubscription -> also don't add anything for unsubscribing to MWDI forwarding
```
  - forwarding-name: ServiceRequestCausesLtpDeletionRequest
    uuid: ro-2-0-1-op-fc-bm-007
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
        - server-name: /v1/redirect-topology-change-information
          uuid: ro-2-0-1-op-s-bm-009
      fc-port-update:
        - server-name: /v1/redirect-topology-change-information
          uuid: ro-2-0-1-op-s-bm-009
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - service-name: /v1/deregister-application
        uuid: ro-2-0-1-op-s-is-002
    consequent-requests:
      - client-name: ApplicationLayerTopology://v1/delete-ltp-and-dependents
        uuid: ro-2-0-1-op-c-bm-alt-1-0-0-002
```
