### ISSUE TITLE
[Code] prepare OAS service is-000 without forwarding

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#161]
Return: 204 - kein Response-Body, nur Info, dass Parameter-Wert aktualisiert wurde

Callbacks: siehe #169
`ControlConstructUpdateCausesNewControlConstructAvailableNotification`
- initiating: /v1/change-parameter-value-in-controlconstruct
- consequent: MicroWaveDeviceInventory:://v1/notify-new-control-construct-available

siehe ForwardingList:
```
  - forwarding-name: ControlConstructUpdateCausesNewControlConstructAvailableNotification
    uuid: mwdi-1-0-0-op-fc-is-020
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/change-parameter-value-in-controlconstruct
        uuid: mwdi-1-0-0-op-s-is-000
    consequent-requests:
      - client-name: MicroWaveDeviceInventory:://v1/notify-new-control-construct-available
        uuid: mwdi-1-0-0-op-s-is-002
```
