### ISSUE TITLE
[Code] Update paths for requests to the Controller

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#202]
Old:
```
        individual:
          ## get list of (all) mounted devices on the controller with connection status
          - operation-name: /rests/data/network-topology:network-topology/topology=topology-netconf?fields=node(node-id;node-id;netconf-node-topology:connection-status)
            uuid: mwdi-1-0-0-op-c-is-c-4-0-2-000
          ## get control construct for a given device (only the non-config part (non-config = PM data + status, should be handled by separate applications))
          - operation-name: /rests/data/network-topology:network-topology/topology=topology-netconf/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct?content=config
            uuid: mwdi-1-0-0-op-c-is-c-4-0-2-001
          ## subscription URL for device status changes (not sure if it needs to be included here)
          - operation-name: /rests/notif/data-change-event-subscription/network-topology:network-topology/datastore=OPERATIONAL/scope=SUBTREE/JSON
            uuid: mwdi-1-0-0-op-c-is-c-4-0-2-002
```
Change paths 1 and 3:
- 000: `/rests/data/network-topology:network-topology/topology=topology-netconf?fields=node(node-id;netconf-node-topology:connection-status)`
- 002: `/rests/notif/{mount-name}?notificationType=device`
