### ISSUE TITLE
Adding OperationClients for Subscribing for Controller Notifications to the ServiceList

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#243]
The ServiceList shall be changed in the following aspect:
- The following OperationClients shall be added to the ODL client stack (HttpClient and TcpClient):
  - /rests/operations/sal-remote:create-data-change-event-subscription
  - /rests/data/ietf-restconf-monitoring:restconf-state/streams/stream/data-change-event-subscription/network-topology:network-topology/datastore=OPERATIONAL/scope=SUBTREE/JSON
    (potentially ?odl-leaf-nodes-only=true to be added to the end)  
  - /rests/notif/data-change-event-subscription/network-topology:network-topology/datastore=OPERATIONAL/scope=SUBTREE/JSON

Proper RequestBodies can be found at [ODL User Guide](https://docs.opendaylight.org/projects/netconf/en/latest/user-guide.html#receiving-netconf-device-notifications-on-a-http-client) chapter _SSE notifications subscription process_.

**Comment by openBackhaul** [comment]
To store the information about the RequestBodies, which we successfully applied:

**https://10.118.125.76:8443/rests/operations/sal-remote:create-data-change-event-subscription**
```
RequestBody:
{
    "input":{
       "path":"/network-topology:network-topology",
        "datastore":"OPERATIONAL",
        "scope":"SUBTREE",
        "sal-remote-augment:notification-output-type":"JSON"
    } 
}
ResponseBody:
{
    "sal-remote:output": {
        "stream-name": "data-change-event-subscription/network-topology:network-topology/datastore=OPERATIONAL/scope=SUBTREE/JSON"
    }
}
```  

**https://10.118.125.76:8443/rests/data/ietf-restconf-monitoring:restconf-state/streams/stream/data-change-event-subscription/network-topology:network-topology/datastore=OPERATIONAL/scope=SUBTREE/JSON**
```
ResponseBody:
{
    "subscribe-to-notification:location": "https://10.118.125.76:8443/rests/notif/data-change-event-subscription/network-topology:network-topology/datastore=OPERATIONAL/scope=SUBTREE/JSON"
}
```

**https://10.118.125.76:8443/rests/notif/data-change-event-subscription/network-topology:network-topology/datastore=OPERATIONAL/scope=SUBTREE/JSON**
(Please note, that it was required to change the Accept header from application/json to \*/\*.)

**Comment by openBackhaul** [comment]
The following changes have been made at the ServiceList, but could not be committed:
```
  - http-client:
      application-name: OpenDaylight
      release-number: 4.0.2
      uuid: mwdi-1-0-0-http-c-c-4-0-2-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.1.1
      tcp-port: 1001
      uuid: mwdi-1-0-0-tcp-c-c-4-0-2-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
          ## DONE: Add Clients specific to this application, but addressing all other applications
          ## none
        individual:
          ## subscribing for controller notifications
          - operation-name: /rests/operations/sal-remote:create-data-change-event-subscription
            uuid: mwdi-1-0-0-op-c-is-c-4-0-2-000
          - operation-name: /rests/data/ietf-restconf-monitoring:restconf-state/streams/stream/data-change-event-subscription/network-topology:network-topology/datastore=OPERATIONAL/scope=SUBTREE/JSON
            uuid: mwdi-1-0-0-op-c-is-c-4-0-2-001
          - operation-name: /rests/notif/data-change-event-subscription/network-topology:network-topology/datastore=OPERATIONAL/scope=SUBTREE/JSON
            uuid: mwdi-1-0-0-op-c-is-c-4-0-2-002

          ## getting list of mounted devices with connection status
          - operation-name: /rests/data/network-topology:network-topology/topology=topology-netconf?fields=node(node-id;netconf-node-topology:connection-status)
            uuid: mwdi-1-0-0-op-c-is-c-4-0-2-010

          ## subscribing for device notifications (repeat for all mounted devices)
          - operation-name: /rests/operations/network-topology:network-topology/topology=topology-netconf/node={mount-name}/yang-ext:mount/notifications:create-subscription
            uuid: mwdi-1-0-0-op-c-is-c-4-0-2-020
          - operation-name: /rests/operations/odl-device-notification:subscribe-device-notification
            uuid: mwdi-1-0-0-op-c-is-c-4-0-2-021
          - operation-name: /rests/notif/{mount-name}?notificationType=device
            uuid: mwdi-1-0-0-op-c-is-c-4-0-2-022

          ## getting control construct (repeat for all connected devices)
          - operation-name: /rests/data/network-topology:network-topology/topology=topology-netconf/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct
            uuid: mwdi-1-0-0-op-c-is-c-4-0-2-030
```
