### ISSUE TITLE
[Code] Align profileInstances for cyclic CC retrieval operation with MATR

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#244]
description attribute does not yet exist in IntegerProfile.
A corresponding ChangeRequest has been created in [AP issue #759](https://github.com/openBackhaul/ApplicationPattern/issues/795).

Until then, the "long" integer-name value shall be stored as comments in the ProfileInstanceList. 
See example from MATR.
```
  - profile-name: 'IntegerProfile'
    uuid: 'matr-1-0-0-integer-p-000'
    capability:
      integer-name: 'slidingWindowSize'
      # description: 'Number of concurrent RPCs (MAC tables of several network elements get retrieved in parallel)'
      minimum: 1
      maximum: 4000
    configuration:
      integer-value: 100

  - profile-name: 'IntegerProfile'
    uuid: 'matr-1-0-0-integer-p-001'
    capability:
      integer-name: 'responseTimeout'
      # description: 'Timeout for receiving the response of the RPC'
      unit: 'second'
      minimum: 5
      maximum: 2000
    configuration:
      integer-value: 60

  - profile-name: 'IntegerProfile'
    uuid: 'matr-1-0-0-integer-p-002'
    capability:
      integer-name: 'maximumNumberOfRetries'
      # description: 'Maximum number of retries for executing an RPC'
      unit:
      minimum: 0
      maximum: 10
    configuration:
      integer-value: 1
```
