### ISSUE TITLE
[Code] Update non-individual forwardings

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#254]
after serviceList entries are finalized the forwardings (+CONFIGfile) need to be updated

**Comment by kmohr-soprasteria** [comment]
remove unsubscribe for section `Potentially add Forwardings for ending INDIVIDUAL subscriptions to OldRelease`

To unsubscribe a DELETE would need to be sent, but this would delete the notification stream for ALL subscribers
(different subscribers do not have dedicated subscription streams!)

To stop receiving the notifications just stop listening, which will be done automatically, once the old release is turned-off

```
# this is done by sending a DELETE request to the subscription URL
  - forwarding-name: PromptForBequeathingDataCausesEndingSubscriptionForDeviceChangeNotificationToOldRelease
    uuid: mwdi-1-0-0-op-fc-im-004
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
      fc-port-update:
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/bequeath-your-data-and-die
        uuid: mwdi-1-0-0-op-s-im-000
    consequent-requests:
      - client-name: OpenDaylight://rests/notif/{mount-name}?notificationType=device
        uuid: mwdi-1-0-0-op-c-is-c-4-0-2-003
```
