### ISSUE TITLE
Check callback completeness in OAS/forwardings/ConfigFile

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#316]
- [x] geprüft: alle individual services enthalten? -> ja
- [x] geprüft: alle Callbacks enthalten? -> *NEIN*
- [x] geprüft: gibt es in der OAS callbacks, die nicht da sein sollten (abgesehen von denen mit falschem Namen aus dem vorherigen Finding)?

Inhaltliche Prüfung der callbacks in eigenem Issue

**Comment by kmohr-soprasteria** [comment]
folgende Callbacks fehlen:
```
NotifiedDeviceObjectCreationCausesReadingOfObjectFromDevice
NotifiedDeviceObjectCreationCausesWritingOfObjectIntoCache
RequestForCachedLtpAugmentPacCausesReadingFromCache
RequestForLiveLtpAugmentPacCausesReadingFromDeviceAndWritingIntoCache
RequestForLivePureEthernetStructureStatusCausesReadingFromDeviceAndWritingIntoCache
RequestForLiveWireInterfaceStatusCausesReadingFromDeviceAndWritingIntoCache
```
(Durch Liste der forwarding/callback-names iteriert und geprüft, ob das forwarding in oas gefunden wird -> bei den obigen Callbacks war der count=0)

**Comment by kmohr-soprasteria** [comment]
Auszug aus Forwarding-Defs:
```
  - forwarding-name: NotifiedDeviceObjectCreationCausesReadingOfObjectFromDevice
    uuid: mwdi-1-0-0-op-fc-is-004
    forwarding-type: InvariantProcessSnippet
    management-requests:
    initiating-requests:
      - server-name: /v1/regard-device-object-creation
        uuid: mwdi-1-0-0-op-s-is-004
    consequent-requests:
      - client-name: OpenDaylight://{controller-internal-path-to-mount-point}/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/equipment={uuid}
        uuid: mwdi-1-0-0-op-c-is-c-4-0-2-410
      - client-name: OpenDaylight://{controller-internal-path-to-mount-point}/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/firmware-1-0:firmware-collection/firmware-component-list={local-id}
        uuid: mwdi-1-0-0-op-c-is-c-4-0-2-421
      - client-name: OpenDaylight://{controller-internal-path-to-mount-point}/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/profile-collection/profile={uuid}
        uuid: mwdi-1-0-0-op-c-is-c-4-0-2-431
      - client-name: OpenDaylight://{controller-internal-path-to-mount-point}/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}
        uuid: mwdi-1-0-0-op-c-is-c-4-0-2-500


  - forwarding-name: NotifiedDeviceObjectCreationCausesWritingOfObjectIntoCache
    uuid: mwdi-1-0-0-op-fc-is-005
    forwarding-type: InvariantProcessSnippet
    management-requests:
    initiating-requests:
      - server-name: /v1/regard-device-object-creation
        uuid: mwdi-1-0-0-op-s-is-004
    consequent-requests:
      - client-name: ElasticSearch://control-construct={mount-name}/equipment={uuid}
        uuid: mwdi-1-0-0-op-c-put-es-1-0-0-410
      - client-name: ElasticSearch://control-construct={mount-name}/firmware-1-0:firmware-collection/firmware-component-list={local-id}
        uuid: mwdi-1-0-0-op-c-put-es-1-0-0-421
      - client-name: ElasticSearch://control-construct={mount-name}/profile-collection/profile={uuid}
        uuid: mwdi-1-0-0-op-c-put-es-1-0-0-431
      - client-name: ElasticSearch://control-construct={mount-name}/logical-termination-point={uuid}
        uuid: mwdi-1-0-0-op-c-put-es-1-0-0-500
```
```
  - forwarding-name: RequestForCachedLtpAugmentPacCausesReadingFromCache
    uuid: mwdi-1-0-0-op-fc-is-201
    forwarding-type: InvariantProcessSnippet
    management-requests:
    initiating-requests:
      - server-name: /core-model-1-4:network-control-domain=cache/control-construct={mount-name}/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac
        uuid: mwdi-1-0-0-op-s-is-201
    consequent-requests:
      - client-name: ElasticSearch://control-construct={mount-name}/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac
        uuid: mwdi-1-0-0-op-c-get-es-1-0-0-201
```
```
  - forwarding-name: RequestForLiveLtpAugmentPacCausesReadingFromDeviceAndWritingIntoCache
    uuid: mwdi-1-0-0-op-fc-is-501
    forwarding-type: InvariantProcessSnippet
    management-requests:
    initiating-requests:
      - server-name: /core-model-1-4:network-control-domain=live/control-construct={mount-name}/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac
        uuid: mwdi-1-0-0-op-s-is-501
    consequent-requests:
      - client-name: OpenDaylight://{controller-internal-path-to-mount-point}/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac
        uuid: mwdi-1-0-0-op-c-is-c-4-0-2-501
      - client-name: ElasticSearch://control-construct={mount-name}/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac
        uuid: mwdi-1-0-0-op-c-put-es-1-0-0-501

  - forwarding-name: RequestForLivePureEthernetStructureStatusCausesReadingFromDeviceAndWritingIntoCache
    uuid: mwdi-1-0-0-op-fc-is-552
    forwarding-type: InvariantProcessSnippet
    management-requests:
    initiating-requests:
      - server-name: /core-model-1-4:network-control-domain=live/control-construct={mount-name}/logical-termination-point={uuid}/layer-protocol={local-id}/pure-ethernet-structure-2-0:pure-ethernet-structure-pac/pure-ethernet-structure-status
        uuid: mwdi-1-0-0-op-s-is-552
    consequent-requests:
      - client-name: OpenDaylight://{controller-internal-path-to-mount-point}/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol={local-id}/pure-ethernet-structure-2-0:pure-ethernet-structure-pac/pure-ethernet-structure-status
        uuid: mwdi-1-0-0-op-c-is-c-4-0-2-552
      - client-name: ElasticSearch://control-construct={mount-name}/logical-termination-point={uuid}/layer-protocol={local-id}/pure-ethernet-structure-2-0:pure-ethernet-structure-pac/pure-ethernet-structure-status
        uuid: mwdi-1-0-0-op-c-put-es-1-0-0-552

  - forwarding-name: RequestForLiveWireInterfaceStatusCausesReadingFromDeviceAndWritingIntoCache
    uuid: mwdi-1-0-0-op-fc-is-572
    forwarding-type: InvariantProcessSnippet
    management-requests:
    initiating-requests:
      - server-name: /core-model-1-4:network-control-domain=live/control-construct={mount-name}/logical-termination-point={uuid}/layer-protocol={local-id}/wire-interface-2-0:wire-interface-pac/wire-interface-status
        uuid: mwdi-1-0-0-op-s-is-572
    consequent-requests:
      - client-name: OpenDaylight://{controller-internal-path-to-mount-point}/node={mount-name}/yang-ext:mount/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol={local-id}/wire-interface-2-0:wire-interface-pac/wire-interface-status
        uuid: mwdi-1-0-0-op-c-is-c-4-0-2-572
      - client-name: ElasticSearch://control-construct={mount-name}/logical-termination-point={uuid}/layer-protocol={local-id}/wire-interface-2-0:wire-interface-pac/wire-interface-status
        uuid: mwdi-1-0-0-op-c-put-es-1-0-0-572
```
