### ISSUE TITLE
Add missing operation-clients in configFile

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#319]
For the operation-clients the entries in the config file are not complete.

E.g. for RO http-client:
```
  - http-client:
      application-name: RegistryOffice
      release-number: 2.0.1
      uuid: mwdi-1-0-0-http-c-ro-2-0-1-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.8
      tcp-port: 3008
      uuid: mwdi-1-0-0-tcp-c-ro-2-0-1-000
    operation-clients:
      own-oam:
        basic:
          - operation-name: /v1/register-application
            uuid: mwdi-1-0-0-op-c-bm-ro-2-0-1-000
          - operation-name: /v1/relay-server-replacement
            uuid: mwdi-1-0-0-op-c-bm-ro-2-0-1-001
          - operation-name: /v1/deregister-application
            uuid: mwdi-1-0-0-op-c-bm-ro-2-0-1-002
          - operation-name: /v1/relay-operation-update
            uuid: mwdi-1-0-0-op-c-bm-ro-2-0-1-003
        individual:
      service:
        basic:
        individual:
```

There is a block for each operation name like 
```
          {
            "uuid": "mwdi-1-0-0-op-c-bm-ro-2-0-1-000",
            "ltp-direction": "core-model-1-4:TERMINATION_DIRECTION_SINK",
            "client-ltp": [
            ],
            "server-ltp": [
              "mwdi-1-0-0-http-c-ro-2-0-1-000"
            ],
            "layer-protocol": [
              {
                "local-id": "0",
                "layer-protocol-name": "operation-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_OPERATION_LAYER",
                "operation-client-interface-1-0:operation-client-interface-pac": {
                  "operation-client-interface-configuration": {
                    "operation-name": "/v1/register-application",
                    "operation-key": "n.a."
                  },
                  "operation-client-interface-status": {
                    "operational-state": "operation-client-interface-1-0:OPERATIONAL_STATE_TYPE_NOT_YET_DEFINED",
                    "life-cycle-state": "operation-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_NOT_YET_DEFINED"
                  }
                }
              }
            ]
          },
```
But for others, like e.g. ElasticSearch those blocks are missing
