### ISSUE TITLE
Wrong usage of stringProfileInstance controllerInternalPathToMountPoint in operation-name?

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#327]
_Possible solution:_
Switch back to use profileInstance uuids instead of the instance name.

_Problem description:_
The string profile for defining the controller internal path prefix might be not used correctly. In the definition the name is in UpperCamelCase, but when the instance is referenced in operation-clients its written with hypens instead.

ProfileInstanceList:
```
  - profile-name: 'StringProfile'
    uuid: 'mwdi-1-0-0-string-p-000'
    capability:
      string-name: 'controllerInternalPathToMountPoint'
    configuration:
      string-value: 'rests/data/network-topology:network-topology/topology=topology-netconf'
```

ServiceList example:
```
          - operation-name: /{controller-internal-path-to-mount-point}?fields=node(node-id;netconf-node-topology:connection-status)
            uuid: mwdi-1-0-0-op-c-is-c-4-0-2-000
```
Is it allowed to use different notations? (if yes, I'm not sure if that's a good idea...)
