### ISSUE TITLE
Missing parameter definitions in both /v1/regard-device-alarm callbacks

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#331]
Solution:
Add responseBody to callback NotifiedDeviceAlarmCausesUpdatingTheEntryInCurrentAlarmListOfCache (to both steps) where the translation from the resource (from /v1/regard-device-alarm) to {mount-name} is made.
Otherwise the mount-name is not known.
Diagram 022_NotificationBasedAlarmListUpdate states 
`mount-name = value behind control-construct= in resource`

---
Problem description:`
`/v1/regard-device-alarm` has callback NotifiedDeviceAlarmCausesUpdatingTheEntryInCurrentAlarmListOfCache.
The related forwarding contains the following 2 consequent-requests:
```
      - client-name: ElasticSearch://control-construct={mount-name}/alarms-1-0:alarm-pac/current-alarms
        uuid: mwdi-1-0-0-op-c-get-es-1-0-0-107
      - client-name: ElasticSearch://control-construct={mount-name}/alarms-1-0:alarm-pac/current-alarms
        uuid: mwdi-1-0-0-op-c-put-es-1-0-0-407
```

With are structured in oas as:
```
callbacks:
  NotifiedDeviceAlarmCausesUpdatingTheEntryInCurrentAlarmListOfCache
    ReadCurrentAlarmListFromCache: ...
    WriteUpdatedCurrentAlarmListToCache: ...
```

In step1 (ReadCurrentAlarmListFromCache) there is no requestBody at all, in step2 (WriteUpdatedCurrentAlarmListToCache) there is a responseBody but it does not contain any information on how the mount-name for the ES-URL is obatined)

**Comment by openBackhaul** [comment]
The following in path parameter definition is to be added to the method definitions:
- NotifiedDeviceAlarmCausesUpdatingTheEntryInCurrentAlarmListOfCache::ReadCurrentAlarmListFromCache::get
- NotifiedDeviceAlarmCausesUpdatingTheEntryInCurrentAlarmListOfCache::WriteUpdatedCurrentAlarmListToCache::put

````
              parameters:
                - name: mount-name
                  in: path
                  required: true
                  schema:
                    type: string
                    example: '222250001'
                  description: >
                    'The mount-name of the device that is addressed by the request
                    from {$request.body#first_part_until_+_in resource}
````
