### ISSUE TITLE
Missing path parameters in callbacks

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#334]
Path-parameters missing in callbacks and need to be added:
- /v1/regard-device-attribute-value-change -> NotifiedDeviceAttributeValueChangeCausesUpdateOfCache
- /v1/regard-device-object-creation -> NotifiedDeviceObjectCreationCausesSelfCallingOfLiveResourcePath
- /v1/regard-device-object-deletion -> NotifiedDeviceObjectDeletionCausesDeletingTheObjectInCache

missing parameters are the same for all:
1. mount-name: required
2. uuid and local-id: optional (depends on actual client)

---
**Problem**:
- OpenAPI does not allow **optional PATH** parameters!
  - tried to include uuid/local-id with "required: false" -> error
  - tried to omit "required" property -> error
  - "required: true" MUST be provided
  - there is an "allowEmptyValue" option, but this is for QUERY parameters (adding it with "required: true" at least shows no error)

---
**Possible solutions:**
1. split each of the forwarding into 3 separate forwardings, each with different path parameters:
    - forwardings-set 1: mount-name
    - forwardings-set 2: mount-name, uuid
    - forwardings-set 3: mount-name, uuid, local-id
 2.  keep the forwardings as they are, but split the existing callbacks into separate blocks:
      see example below. not sure if this is even possible, because of the uuids
 4. maybe we can somehow work with profileInstances? (if this works, it might make everything just overly complicated)
 5. if possible, work with the allowEmptyValue even if not intended for path parameters 

**we should find a solution before SIAE has started implementing those callbacks**

**Comment by kmohr-soprasteria** [comment]
Excerpt of consequent requests for NotifiedDeviceAttributeValueChangeCausesUpdateOfCache:
```
# just mount-name
      - client-name: ElasticSearch://control-construct={mount-name}
        uuid: mwdi-1-0-0-op-c-get-es-1-0-0-100
# mount-name and uuid
      - client-name: ElasticSearch://control-construct={mount-name}/equipment={uuid}/connector={local-id}
        uuid: mwdi-1-0-0-op-c-get-es-1-0-0-111
# mount-name, uuid, and local-id
      - client-name: ElasticSearch://control-construct={mount-name}/equipment={uuid}/expected-equipment={local-id}
        uuid: mwdi-1-0-0-op-c-get-es-1-0-0-113
```

**Comment by kmohr-soprasteria** [comment]
Example for path-parameter mount-name from callback NotifiedDeviceAlarmCausesUpdatingTheEntryInCurrentAlarmListOfCache:
```
        NotifiedDeviceAlarmCausesUpdatingTheEntryInCurrentAlarmListOfCache:
          ReadCurrentAlarmListFromCache: #[/core-model-1-4:control-construct/logical-termination-point=mwdi-1-0-0-tcp-c-es-1-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-protocol]://[/core-model-1-4:control-construct/logical-termination-point=mwdi-1-0-0-tcp-c-es-1-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/domain-name or /core-model-1-4:control-construct/logical-termination-point=mwdi-1-0-0-tcp-c-es-1-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/ip-address/ipv-4-address]:[/core-model-1-4:control-construct/logical-termination-point=mwdi-1-0-0-tcp-c-es-1-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port][/core-model-1-4:control-construct/logical-termination-point=mwdi-1-0-0-op-c-get-es-1-0-0-107/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]
            get:
              parameters:
                - name: mount-name
                  in: path
                  required: true
                  schema:
                    type: string
                    example: '222250001'
                  description: >
                    'The mount-name of the device that is addressed by the request
                    from {$request.body#value_behind_control-construct=_in_resource}
```

And other examples for uuid and local-id WITH required: true from other callbacks:
                - name: uuid
                  in: path
                  required: true
                  schema:
                    type: string
                    example: 'LTP-MWPS-TTP-1-1'
                  description: >
                    'The UUID of the Equipment that is addressed by the request
                    from {$request.parameters#uuid}'

                - name: local-id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: 'LP-MWPS-TTP-1-1'
                  description: >
                    'The Local-ID of the Connector that is addressed by the request
                    from {$request.parameters#local-id}'
