### ISSUE TITLE
Remove usage of fields filter in ServiceList (+ correct wrong block for stringProfileInstance in configFile)

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#335]
The fields filter is used in the serviceList for
```
          ## GET list of mounted devices with connection status from Controller
          - operation-name: /{controller-internal-path-to-mount-point}?fields=node(node-id;netconf-node-topology:connection-status)
            uuid: mwdi-1-0-0-op-c-is-odl-4-0-2-000
```

- The fields filter shall be removed from the ServiceList and only be used in the OAS
- A string profile for the fields filter value shall be created (added to profileInstancesList and configFile) and shall be referenced in the path-parameters definition of the related callback
- see examples in AutomatedLinkAcceptanceProxy specification

**Comment by kmohr-soprasteria** [comment]
Fields filter now no longer part of the operation-client -> needs to be provided as query parameter in callback.
(Derived from alap example) this leads to:
```
                - name: fields
                  in: query
                  required: true
                  schema:
                    type: string
                    example: 'node(node-id;netconf-node-topology:connection-status)'
                  description: >
                    'If different from empty string, a fields filter with the following value to be added to the request
                    from [/core-model-1-4:control-construct/profile-collection/profile=mwdi-1-0-0-string-p-001/string-profile-1-0:string-profile-pac/string-profile-configuration/string-value]'
```
