### ISSUE TITLE
Add proper examples for cache/link services

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#809]
Add proper examples for the cache/link services for better understanding of the services:
-  /core-model-1-4:network-control-domain=cache/link={uuid}
-  /core-model-1-4:network-control-domain=cache/link={uuid}/link-port={localId}

**Comment by kmohr-soprasteria** [comment]
todo:
1. example for link: generic, minimum for rest
2. example for link_port: generic

(1) Minimum for rest example:
```
core-model-1-4:link:
  - uuid: '530557202'
    layer-protocol-name: 'core-model-1-4:LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER'
    end-point-list:
      - control-construct: '530270703'
        logical-termination-point: '530270703+RF-2146435217'
        layer-protocol: '530270703+2146435217'
      - control-construct: '530270705'
        logical-termination-point: '530270705+RF-2146435217'
        layer-protocol: '530270705+2146435217'
 - uuid: '513559997‘
    layer-protocol-name: 'core-model-1-4:LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER'
    end-point-list:
      - control-construct: '530270703'
        logical-termination-point: '530270703+RF-2146435233'
        layer-protocol: '530270703+2146435233'
      - control-construct: '530270705'
        logical-termination-point: '530270705+RF-2146435233'
        layer-protocol: '530270705+2146435233'
```


---
some examples derived from testbed and live NEs:
![image](https://github.com/openBackhaul/MicroWaveDeviceInventory/assets/57349523/6bff5233-5f78-46eb-a365-f7baedc25a08)
