### ISSUE TITLE
/core-model-1-4:network-control-domain=cache/link={uuid}/link-port={local-id} - error response message for unknown NEs needs to be changed

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#969]
If the cache doesn't contain data for the combination of uuid/local-id the service returns a 404 for both GET and DELETE, which is correct.
However the responseMessages need to be modified, as they currently both return "unable to fetch records for link >uuid<".

They should be changed as follows:
- GET: "unable to fetch records for linkport >uuid</>local-id<"
- DELETE: "unable to delete records for linkport >uuid</>local-id<"

**Comment by Ziabatcha** [comment]
Tested with latest package 1.1.2e, Issue still persist.

```
observing Null response when trying to GET a link port that doesnt exists.

http://xxx:xxx/core-model-1-4:network-control-domain=cache/link=513250008/link-port=3

{
  "core-model-1-4:link-port": [
    null
  ]
}

```


```
observing 204 RESPONSE when trying to DELETE a link port that doesnt exists.

http://xxx:xxx/core-model-1-4:network-control-domain=cache/link=513250008/link-port=4

Response:
access-control-allow-origin: * 
 connection: keep-alive 
 date: Wed, 19 Jun 2024 06:09:48 GMT 
 keep-alive: timeout=5 
 x-powered-by: Express


```
