### ISSUE TITLE
Harmonization of HTTP response codes

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/MicroWaveDeviceInventory#997]
The [response codes defined in the ApplicationPattern](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/HowToDefineErrorMessages/HowToDefineErrorMessages.md) shall be copied into the openAPI specification and become part of the implementation.

Also: 
- Where necessary the implementation would need to be changed (separate issue) 
- in the previous release(s) there were no fixed prescriptions for the error messages to be returned by MWDI in specific error cases. This shall be done now.
- standard responseCodes should return the standard message (e.g. 429: too many parallel requests) instead of custom messages

**Comment by kmohr-soprasteria** [comment]
All of the responses from the "List of internally defined response codes" are added to the components section.
However:
- not all response codes are relevant for the MWDI at all
- some may be relevant for specific services only, but not for all services

**Comment by kmohr-soprasteria** [comment]
- ressource paths:
  - cache: no additional 5xx, as errors here are on client (MWDI) side, not from the controller (5xx)
  - live: 502, 530, 531, 532

**Comment by kmohr-soprasteria** [comment]
There are different service classes to be considered:

 service categories
 1. notification receipt
 2. ordinary services:
    - device based
    - link/link port based
    - metadata
 3. subscription services
 4. ressource path services - LINK (cache)
 5. ressource path services - nonLink cache
 6. ressource path services - nonLink live

**Comment by kmohr-soprasteria** [comment]
**Notification receipt services**
- **operation-name: /v1/regard-controller-attribute-value-change**
   - service itself: no changes
   - callbacks:
      - [server] NotifiedNewDeviceCausesSelfCallingForLoadingOfControlConstruct: 
         - queries controller: add 502, 530, 531, 532
      - [client] NotifiedDisconnectedDeviceCausesDeviceDeletionFromCache
         - 404 should suffice
- **operation-name: /v1/regard-device-alarm**
   - service itself: <todo>
   - callbacks:
      - [client] NotifiedDeviceAlarmCausesUpdatingTheEntryInCurrentAlarmListOfCache
         - ReadCurrentAlarmListFromCache
         - WriteUpdatedCurrentAlarmListToCache
            - add 470: theoretically the ressource for which the alarm is coming, could not be found in the ControlConstruct (if e.g. the previously received CC was incomplete)
  - **operation-name: /v1/regard-device-attribute-value-change**
        # - 470: die Ressource ist nicht da
        # callbacks:
        #   NotifiedDeviceAttributeValueChangeCausesUpdateOfCache
        #     ReadClass.get: -> 470 theoretisch könnte es sein, dass die Ressource nicht da ist (z.B. weil vorheriges CC Update fehlt)
        #     UpdateAndWriteClass.put -> 470 (falls das ReadClass ein 470 geliefert hat)
- **operation-name: /v1/regard-device-object-creation**
        # - 533: wenn die Ressource nicht auf dem Gerät exististiert kommt ein Fehler! (CTRL) (NEUEN CODE HINZUFÜGEN!) ===>
        #   SICHERHEITSHALBER NOCHMAL PRÜFEN, OB DAS MWDI DA AUCH EINE FEHLERMELDUNG JETZT SCHON LIEFERT (kann auch einfach nur ein 204, notification received sein!)
        # callbacks:
        #   NotifiedDeviceObjectCreationCausesSelfCallingOfLiveResourcePath (get)
        #   (der Controller gibt hier seine eigene Error Response zurück; die 533 wird nicht vom callback zurückgegeben (der Callback geht ja auf den Controller, d.h. der Callback hat auch nur die COntroller-Responses!))
- **operation-name: /v1/regard-device-object-deletion**
        # analog zur object creation: 533 
        # callbacks:
        #   NotifiedDeviceObjectDeletionCausesDeletingTheObjectInCache (delete)

**Comment by kmohr-soprasteria** [comment]
**Ordinary services**
- operation-name: /v1/provide-list-of-connected-devices
   - keine neuen Codes
   - callbacks:
   -   RequestForListOfConnectedDevicesCausesReadingFromCache (get)
- operation-name: /v1/provide-list-of-device-interfaces
   - 460: device not in deviceList
   - callbacks:
   -   RequestForListOfDeviceInterfacesCausesReadingFromCache (get)
   -   (460: device not in deviceList)
- operation-name: /v1/provide-list-of-actual-device-equipment
   - 460: device not in deviceList
   - callbacks:
   -   RequestForListOfActualDeviceEquipmentCausesReadingFromCache (get)
   -   (460: device not in deviceList)
- operation-name: /v1/provide-list-of-parallel-links
   - 461: if link from requestBody is not found in cache (if callbacks return 471)
   - callbacks:
   -   RequestForListOfParallelLinksCauses
   -     ReadingEndpointsFromCache (get): ruft einen Ressource-Path auf dem ES auf (link=uuid)
   -     SearchingParallelLinksInCache (get): ruft auch einen Ressource-Path auf
   -     bei beiden: wenn nicht gefunden: 471: link/topology item from service path not found
- operation-name: /v1/provide-list-of-links
   - default codes remain, if nothing found, returns just empty list
   - callbacks: / (direkt ES): nothing to add
- operation-name: /v1/provide-list-of-link-ports
   - default codes remain, if nothing found, returns just empty list
   - callbacks: / (direkt ES): nothing to add
- operation-name: /v1/provide-data-of-all-links
   - default codes remain, if nothing found, returns just empty list
   - callbacks: / (direkt ES): nothing to add
- operation-name: /v1/provide-data-of-all-link-ports
   - default codes remain, if nothing found, returns just empty list
   - callbacks: / (direkt ES): nothing to add
- operation-name: /v1/provide-device-status-metadata
   - service itself: keine Zusatzinfos
   - es wird eine Liste von devices übergeben, wenn man zu denen nichts findet, werden die einfach ignoriert, im worst case wird eine leere Liste zurückgegeben
   - d.h. wenn was nicht gefunden wird, gibt es keinen Fehler, eine Fehlerbehandlung muss dann ggf. auf Seiten des Aufrufers geschehen: der muss die Anforderungsliste mit der Ergebnisliste vergleichen und ggf. bei sich als Fehler behandeln
   - callbacks: / (direkt ES)

**Comment by kmohr-soprasteria** [comment]
**Subscription services**
- all: just default responseCodes, no additional codes required
- services:
  - operation-name: /v1/notify-attribute-value-changes
      - callbacks: SubscribingAtMwdiForDeviceAttributeChangesCausesSendingNotifications (post)
  - operation-name: /v1/notify-object-creations
      - callback: SubscribingAtMwdiForDeviceObjectCreationsCausesSendingNotifications (post)
  - operation-name: /v1/notify-object-deletions
      - callback: SubscribingAtMwdiForDeviceObjectDeletionsCausesSendingNotifications (post)

**Comment by kmohr-soprasteria** [comment]
**Link/Link-Port (topology) ressource path services**
- link service (cache): /core-model-1-4:network-control-domain=cache/link={uuid}
  - put:
    - nothing to add
    - callback: RequestForUpdatingLinkCausesWritingIntoCache (put)
  - get:
    - add 461: the link (parent topology object) is not found in the cache 
    - callback: RequestForCachedLinkCausesReadingFromCache (get)
      - add 461
  - delete:
    - add 461
    - callback: RequestForDeletingLinkCausesDeletingFromCache (delete)
      - add 461

- linkport service (cache): /core-model-1-4:network-control-domain=cache/link={uuid}/link-port={localId}
  - put:
    - add 461: returned, if the parent topology object (link) is not found in the cache
    - callback: RequestForUpdatingLinkPortCausesWritingIntoCache (put)
      - add 461
  - get:
    - add 461 (link not found)
    - add 471 (link found, but linkport not found)
    - callback: RequestForCachedLinkPortCausesReadingFromCache (get)
      - add 461, 471
  - delete:
    - add 461 (link not found)
    - add 471 (link found, but linkport not found)
    - callback: RequestForDeletingLinkPortCausesDeletingFromCache (delete)
      - add 461, 471

**Comment by kmohr-soprasteria** [comment]
New error codes, which need to be added to the appPattern documentation:

461: 
- this responseCode is similar to 460, but 460 is targeting devices, which are not in connected state (and thus, not found in the MWDI)
- 461 however, is targeting objects != devices, i.e. topology/enrichment objects like links; note that these objects are parent objects
- the parent topology object can be provided in the path or requestBody
   - note: an unknown object in the path would normally be a 404 (not found), as the URL becomes invalid, but for better transparency on problem causes this error should be represented by a 461 instead (and the same would normally go for 460)
```
    '461':
      description: 'Response in case the (parent) topology object provided in the request (body or path) is not found in the cache.'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 461
                maximum: 461
                format: int32
              message:
                type: string
                enum:
                  - 'Not available. The topology (parent) object is currently not found in the cache.'
```

471:
- this responseCode is similar to 470, but 470 targets not found ressources on an existing device
- 471 however, targets child topology/enrichment objects, like link-ports (where link is the parent object)
- again the child topology object can be provided in the path or requestBody (again, this would normally be a 404, but for better transparency the 471 shall be used (the same for 470)) 
```
    '471':
      description: 'Response in case the (child) topology object specified in the request (body or path) does not exist within the cache.'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 471
                maximum: 471
                format: int32
              message:
                type: string
                enum:
                  - '(Child) topology object not existing. Cache informs about addressed resource unknown.'
```

533:
- this responseCode to be used in case a ressource should be addressed for a device that is connected at the Controller
- this is relevant for the device-object-creation and device-object-deletion (if the MWDI e.g. receives a notification about a created object, it tries to retrieve that object from the Controller, but if it cannot be found there, the MWDI will see an error.
```
    '533':
      description: 'Response in case the referenced ressource for an connected device does not exist at the controller.'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 533
                maximum: 533
                format: int32
              message:
                type: string
                enum:
                  - 'Ressource unknown. The ressource for the connected device does not exist at the Controller.'
```
